### ISSUE TITLE
Can you release a finished product?

### ISSUE THREAD

**Issue by ttsite** [Kudaes/Elevator#1]
Can you release a finished product? There is no compilation environment on this machine. Thank you!

**Comment by Kudaes** [comment]
Hi @ttsite,

I won't release a compiled version of this project for now. Anyway, it should be pretty easy to get a working environment where you can compile the code. You just need to download and run the Rust installer from [here](https://www.rust-lang.org/tools/install). After that, just follow the compilation instructions from the Readme.

**Comment by ThrowAwayAccount00** [comment]
@ttsite  here you go [elevator.zip](https://github.com/Kudaes/Elevator/files/9491658/elevator.zip)

only requires approx 1.4 GBs of 'Visual Studio Downloads' just to get a 325 KB executable :)

![FFS](https://user-images.githubusercontent.com/112900488/188504349-d1260acd-14f7-490c-8617-90538db0ac4a.gif)
