### ISSUE TITLE
Initial process creation debug event not received

### ISSUE THREAD

**Issue by jakemarston** [Kudaes/Elevator#4]
I get the following error when running `elevator.exe --new-console C:\windows\System32\cmd.exe`
```
[+] Unelevatad notepad.exe process created.
[+] Reference to debug object retrieved.
[+] Debug object successfully detached.
[+] Elevated taskmgr.exe process created.
[+] Initial process creation debug event obtained.
[+] Full access handle obtained.
[x] The new process could not be spawned.
```

**Comment by Kudaes** [comment]
Hi @jakemarston,

The parameters are not position independient. Try running elevator.exe C:\windows\System32\cmd.exe --new-console instead.

The first parameter should always be the command line that you want to execute.

**Comment by jakemarston** [comment]
Thanks this worked
