### ISSUE TITLE
RPC call to RAiLaunchAdminProcess failed

### ISSUE THREAD

**Issue by jc1396** [Kudaes/Elevator#6]
Not sure this is an issue, but when I tested this on a very hardened system, I get an "RPR call to RAiLaunchAdminProcess failed" message.  Any suggestions?

**Comment by Kudaes** [comment]
Hi, may you give me more details about what do you mean with "a very hardened system"? 
Is the user running the  tool member of the Administrator group?
Is the UAC policy set to "Always notify"?
